services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: social-backend
    ports:
      - "8000:8000"
    volumes:
      - ./sqlite:/app/sqlite
    environment:
      PYTHONUNBUFFERED: "1"
      RABBIT_HOST: rabbitmq
    env_file:
      - .env
    networks:
      - social-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NGINX_CONF: nginx.conf
    container_name: social-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - social-net

  rabbitmq:
    image: rabbitmq:management
    container_name: social-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - social-net

  image-resizer:
    build: ./image-resizer
    container_name: social-image-resizer
    depends_on:
      rabbitmq:
        condition: service_healthy
      backend:
        condition: service_started
    volumes:
      - ./sqlite:/app/sqlite
    networks:
      - social-net


  post_ai_generation:
    build:
      context: post_ai_generation
      dockerfile: Dockerfile
    container_name: social-post_ai_generation
    volumes:
      - ~/hf_models:/hf_models
    environment:
      - RABBIT_HOST=rabbitmq
      - BACKEND_URL= http://backend:8000
      - MODEL_PATH= /hf_models/bloomz-560m
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - social-net

networks:
  social-net:
    name: network-social
    driver: bridge

volumes:
  rabbitmq_data:
  hf_models:
